name: CNN CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r app/requirements.txt

    - name: Run model training (if needed)
      run: |
        echo "Training can be automated if moved into a script."

    - name: Run evaluation (if needed)
      run: |
        echo "You can also automate evaluation if needed."
